package vokabeltrainer.resources;

import vokabeltrainer.common.ApplicationSound;
import vokabeltrainer.editing.SwedishLetter;

public class Sounds
{
   public static void read() throws Exception
   {
      ApplicationSound.setSplotchSound(Sounds.class.getResourceAsStream(
            "sounds/splotch-sound.byt"));
      ApplicationSound.setClappingSound(Sounds.class.getResourceAsStream(
            "sounds/clapping-sound.byt"));
      ApplicationSound.setWaveSound(Sounds.class
            .getResourceAsStream("sounds/wave-sound.byt"));
      ApplicationSound.setShredderSound(Sounds.class.getResourceAsStream(
            "sounds/shredder-sound.byt"));

      SwedishLetter.A.setSound(Sounds.class
            .getResourceAsStream("sounds/A.byt"));
      SwedishLetter.a.setSound(Sounds.class
            .getResourceAsStream("sounds/A.byt"));
      SwedishLetter.B.setSound(Sounds.class
            .getResourceAsStream("sounds/B.byt"));
      SwedishLetter.b.setSound(Sounds.class
            .getResourceAsStream("sounds/B.byt"));
      SwedishLetter.C.setSound(Sounds.class
            .getResourceAsStream("sounds/C.byt"));
      SwedishLetter.c.setSound(Sounds.class
            .getResourceAsStream("sounds/C.byt"));
      SwedishLetter.D.setSound(Sounds.class
            .getResourceAsStream("sounds/D.byt"));
      SwedishLetter.d.setSound(Sounds.class
            .getResourceAsStream("sounds/D.byt"));
      SwedishLetter.E.setSound(Sounds.class
            .getResourceAsStream("sounds/E.byt"));
      SwedishLetter.e.setSound(Sounds.class
            .getResourceAsStream("sounds/E.byt"));
      SwedishLetter.F.setSound(Sounds.class
            .getResourceAsStream("sounds/F.byt"));
      SwedishLetter.f.setSound(Sounds.class
            .getResourceAsStream("sounds/F.byt"));
      SwedishLetter.G.setSound(Sounds.class
            .getResourceAsStream("sounds/G.byt"));
      SwedishLetter.g.setSound(Sounds.class
            .getResourceAsStream("sounds/G.byt"));
      SwedishLetter.H.setSound(Sounds.class
            .getResourceAsStream("sounds/H.byt"));
      SwedishLetter.h.setSound(Sounds.class
            .getResourceAsStream("sounds/H.byt"));
      SwedishLetter.I.setSound(Sounds.class
            .getResourceAsStream("sounds/I.byt"));
      SwedishLetter.i.setSound(Sounds.class
            .getResourceAsStream("sounds/I.byt"));
      SwedishLetter.J.setSound(Sounds.class
            .getResourceAsStream("sounds/J.byt"));
      SwedishLetter.j.setSound(Sounds.class
            .getResourceAsStream("sounds/J.byt"));
      SwedishLetter.K.setSound(Sounds.class
            .getResourceAsStream("sounds/K.byt"));
      SwedishLetter.k.setSound(Sounds.class
            .getResourceAsStream("sounds/K.byt"));
      SwedishLetter.L.setSound(Sounds.class
            .getResourceAsStream("sounds/L.byt"));
      SwedishLetter.l.setSound(Sounds.class
            .getResourceAsStream("sounds/L.byt"));
      SwedishLetter.M.setSound(Sounds.class
            .getResourceAsStream("sounds/M.byt"));
      SwedishLetter.m.setSound(Sounds.class
            .getResourceAsStream("sounds/M.byt"));
      SwedishLetter.N.setSound(Sounds.class
            .getResourceAsStream("sounds/N.byt"));
      SwedishLetter.n.setSound(Sounds.class
            .getResourceAsStream("sounds/N.byt"));
      SwedishLetter.O.setSound(Sounds.class
            .getResourceAsStream("sounds/O.byt"));
      SwedishLetter.o.setSound(Sounds.class
            .getResourceAsStream("sounds/O.byt"));
      SwedishLetter.P.setSound(Sounds.class
            .getResourceAsStream("sounds/P.byt"));
      SwedishLetter.p.setSound(Sounds.class
            .getResourceAsStream("sounds/P.byt"));
      SwedishLetter.Q.setSound(Sounds.class
            .getResourceAsStream("sounds/Q.byt"));
      SwedishLetter.q.setSound(Sounds.class
            .getResourceAsStream("sounds/Q.byt"));
      SwedishLetter.R.setSound(Sounds.class
            .getResourceAsStream("sounds/R.byt"));
      SwedishLetter.r.setSound(Sounds.class
            .getResourceAsStream("sounds/R.byt"));
      SwedishLetter.S.setSound(Sounds.class
            .getResourceAsStream("sounds/S.byt"));
      SwedishLetter.s.setSound(Sounds.class
            .getResourceAsStream("sounds/S.byt"));
      SwedishLetter.T.setSound(Sounds.class
            .getResourceAsStream("sounds/T.byt"));
      SwedishLetter.t.setSound(Sounds.class
            .getResourceAsStream("sounds/T.byt"));
      SwedishLetter.U.setSound(Sounds.class
            .getResourceAsStream("sounds/U.byt"));
      SwedishLetter.u.setSound(Sounds.class
            .getResourceAsStream("sounds/U.byt"));
      SwedishLetter.V.setSound(Sounds.class
            .getResourceAsStream("sounds/V.byt"));
      SwedishLetter.v.setSound(Sounds.class
            .getResourceAsStream("sounds/V.byt"));
      SwedishLetter.W.setSound(Sounds.class
            .getResourceAsStream("sounds/W.byt"));
      SwedishLetter.w.setSound(Sounds.class
            .getResourceAsStream("sounds/W.byt"));
      SwedishLetter.X.setSound(Sounds.class
            .getResourceAsStream("sounds/X.byt"));
      SwedishLetter.x.setSound(Sounds.class
            .getResourceAsStream("sounds/X.byt"));
      SwedishLetter.Y.setSound(Sounds.class
            .getResourceAsStream("sounds/Y.byt"));
      SwedishLetter.y.setSound(Sounds.class
            .getResourceAsStream("sounds/Y.byt"));
      SwedishLetter.Z.setSound(Sounds.class
            .getResourceAsStream("sounds/Z.byt"));
      SwedishLetter.z.setSound(Sounds.class
            .getResourceAsStream("sounds/Z.byt"));
      SwedishLetter.AE.setSound(Sounds.class
            .getResourceAsStream("sounds/AE.byt"));
      SwedishLetter.ae.setSound(Sounds.class
            .getResourceAsStream("sounds/AE.byt"));
      SwedishLetter.ARING.setSound(Sounds.class
            .getResourceAsStream("sounds/ARING.byt"));
      SwedishLetter.aring.setSound(Sounds.class
            .getResourceAsStream("sounds/ARING.byt"));
      SwedishLetter.OE.setSound(Sounds.class
            .getResourceAsStream("sounds/OE.byt"));
      SwedishLetter.oe.setSound(Sounds.class
            .getResourceAsStream("sounds/OE.byt"));
      SwedishLetter.SPACE.setSound(Sounds.class
            .getResourceAsStream("sounds/SPACE.byt"));
   }
}
